apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
  labels:
    app: grafana
spec:
  selector:
    app: grafana
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 31342
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: grafana-pvc-claim
spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: grafana-deploy
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana-pod
      labels:
        app: grafana
    spec: 
      containers:
        - name: graf-storage
          image: vimal13/grafana
          volumeMounts:
            - name: graf-persistent-storage
              mountPath: /var/lib/grafana
      volumes:
        - name: graf-persistent-storage
          persistentVolumeClaim:
              claimName: grafana-pvc-claim