apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  labels:
    app: prometheus
spec:
  selector:
    app: prometheus
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 31815
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prom-pvc-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: prometheus-deploy
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  strategy:
    type: Recreate
  template:
    metadata:
      name: prometheus-pod
      labels:
        app: prometheus
    spec:
      containers:
      - name: prom
        image: vimal13/prometheus
        volumeMounts:
        - name: prom-persistent-storage
          mountPath: /prometheus/
      volumes:
      - name: prom-persistent-storage
        persistentVolumeClaim:
          claimName: prom-pvc-claim
